baseURL = "https://light-org.vercel.app"
languageCode = "en-us"
title = "The Lay Institute for Global Health Training | Training Medical Missionaries Worldwide"
[build]
writeStats = true
[[menu.footer]]
name = "church-courses"
parent = "Church Training"
title = "Courses"
weight = 2
[[menu.footer]]
name = "church-overview"
parent = "Church Training"
title = "Overview"
weight = 1
[[menu.footer]]
name = "news"
title = "News"
weight = 12
[[menu.footer]]
name = "store"
title = "Store"
weight = 11
[[menu.footer]]
name = "about-board"
parent = "about"
title = "Board / Staff"
weight = 9
[[menu.footer]]
name = "about-work"
parent = "about"
title = "Our Work"
weight = 8
[[menu.footer]]
name = "about-who"
parent = "about"
title = "Who We Are"
weight = 7
[[menu.footer]]
name = "individual-on-site"
parent = "individual"
title = "On-Site Training"
weight = 4
[[menu.footer]]
name = "individual-courses"
parent = "individual"
title = "Courses"
weight = 3
[[menu.footer]]
name = "individual-overview"
parent = "individual"
title = "Overview"
weight = 2
[[menu.main]]
name = "Sign Up"
title = "Sign Up"
url = "https://lightingtheworld.digitalchalk.com/auth/organization/find"
weight = 4
[menu.main.params]
class = "button border-powder-blue px-6 py-2 border-2 rounded"
[[menu.secondary]]
name = "our-work"
title = "Our Work"
url = "/our-work"
weight = 2
[[menu.secondary]]
name = "news"
title = "News"
url = "/blog/"
weight = 3
[[menu.secondary]]
name = "store"
title = "Store"
url = "/store"
weight = 4
[[menu.social]]
name = "header-instagram"
parent = "header"
pre = "img/nav-icon-instagram.svg"
weight = 3
[[menu.social]]
name = "header-twitter"
parent = "header"
pre = "img/nav-icon-twitter.svg"
weight = 2
[[menu.social]]
name = "header-facebook"
parent = "header"
pre = "img/nav-icon-facebook.svg"
weight = 1
[[menu.social]]
name = "footer-instagram"
parent = "footer"
pre = "img/footer-instagram.svg"
weight = 6
[[menu.social]]
name = "footer-twitter"
parent = "footer"
pre = "img/footer-twitter.svg"
weight = 5
[[menu.social]]
name = "footer-facebook"
parent = "footer"
pre = "img/footer-facebook.svg"
weight = 4
[permalinks]
blog = "/blog/:year/:month/:filename/"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
